apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deploiement
spec:
  replicas: 5
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: python-app:v1  
        ports:
        - containerPort: 5000

